import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("the model owns an evolving creative direction rather than a runtime aesthetic score", () => {
  const types = readFileSync("lib/canvas-v2/types.ts", "utf8");
  const route = readFileSync("app/api/canvas-v2/design/route.ts", "utf8");
  const loop = readFileSync("lib/canvas-v2/design-loop.ts", "utf8");

  assert.match(types, /interface CanvasV2CreativeDirection/);
  assert.match(types, /interface CanvasV2RenderedReflection/);
  assert.match(types, /unresolvedOpportunities: string\[\]/);
  for (const read of ["conceptRead", "hierarchyRead", "evidenceRead", "relationshipRead", "legibilityRead", "distinctivenessRead"]) {
    assert.match(types, new RegExp(`${read}: string`));
  }
  assert.match(route, /visual director/);
  assert.match(route, /preserve them as an explicit preservation contract/);
  assert.match(route, /server owns those responsibilities/);
  assert.match(loop, /creativeDirection: input\.creativeDirection/);
  assert.doesNotMatch(`${types}\n${loop}`, /aestheticScore|visualScore|scoreThreshold/);
});

test("creative moves are purposeful and remain open to divergent visual forms", () => {
  const route = readFileSync("app/api/canvas-v2/design/route.ts", "utf8");
  const grammar = readFileSync("lib/canvas-v2/northstar-artboard-grammar.ts", "utf8");

  for (const move of ["framing", "composition", "relationship", "analysis", "refinement"]) {
    assert.match(route, new RegExp(`\\"${move}\\"`));
  }
  assert.match(route, /original hybrid/);
  assert.match(route, /never prescribed templates/);
  assert.match(grammar, /editorial intelligence/);
  assert.match(grammar, /artifact-scoped CSS with custom properties/);
  assert.match(grammar, /Avoid returning the same header-plus-cards composition/);
  assert.match(grammar, /complete-artboard overview as a first-class reading distance/);
  assert.match(route, /Progressive judgment without a creative-turn ceiling/);
  assert.match(route, /North Star visual-language references/);
  assert.match(route, /strategic-storyline-atlas\.png/);
  assert.match(route, /evidence-constellation\.png/);
  assert.match(route, /quick-visible-foundation/);
  assert.match(route, /progressive-visible-development/);
  assert.match(route, /phase: "integration"/);
  assert.match(route, /phase: "convergence"/);
  assert.match(route, /phase: "final-review"/);
  assert.match(route, /observedDesignTurns < 15/);
  assert.match(route, /observedDesignTurns < 18/);
  assert.match(route, /Every visible synthesis turn starts with a compact whole-board judgment/);
  assert.match(route, /repeatedLocalWork/);
  assert.match(route, /REPETITION_GENERIC_MOVE_TERMS/);
  assert.match(route, /sharedDistinctiveMoveTerms/);
  assert.match(route, /must compare the authored device, not the vocabulary/);
  assert.match(route, /REPETITION REDIRECTION/);
  assert.match(route, /PHASE AUTHORITY/);
  assert.match(route, /Do not recommend completion/);
  assert.match(route, /Zones already carrying authored design regions/);
  assert.match(route, /maxInvalidResponsesPerModel: 4/);
  assert.match(route, /do not emit a no-op CSS patch, continuity edit, or speculative polish turn/);
  assert.match(route, /A visible design turn must make one material rendered change/);
  assert.match(route, /directorCompletionDecision/);
  assert.match(route, /creativeCheckpointBrief\?\.completionRecommendation === "complete"/);
  assert.match(route, /deterministic completion checks found a concrete visible omission/);
  assert.match(route, /missingIdentitySelections/);
  assert.match(route, /completion-integrity-repair/);
  assert.match(route, /validator-required completion repair/);
  assert.match(route, /rename or repeat that repair under another move kind/);
  assert.match(route, /Convergence is part of visual judgment/);
  assert.match(route, /repeatedPair \|\| repeatedSequence/);
  assert.match(route, /Do not rename or repeat that repair/);
  assert.match(route, /Repetition and diminishing returns are visual-direction context/);
  assert.match(route, /targetIsland/);
  assert.match(route, /buildCanvasV2IslandRegistry/);
  assert.match(route, /islandRegistry\.length === 0/);
  assert.match(route, /canvasV2AllocatedIslandId/);
  assert.match(route, /focusedIslandSource/);
  assert.match(route, /compactCanvasV2IslandSourceForModel/);
  assert.match(route, /newlyRequiredEvidenceIds/);
  assert.match(route, /missingAfterPatch/);
  assert.match(route, /bindCanvasV2SelectedEvidenceToExistingIsland/);
  assert.match(route, /Existing island \$\{targetId\} is durable/);
  assert.match(route, /Never remove or replace its top-level node/);
  assert.match(route, /Focused target-island capture/);
  assert.match(route, /Create must target the exact server-allocated island identity/);
  assert.match(route, /develop, enrich, or repair, choose an exact existing island ID/);
  assert.match(route, /resultingMaturity/);
  assert.match(route, /openRequirements/);
  assert.match(route, /Never use whole-board completion to fabricate resolved island state/);
  assert.match(route, /Whole-board completion is blocked by unfinished island lifecycle state/);
  assert.doesNotMatch(route, /regions: input\.compositionState\.regions\.map\(\(region\) => \(\{ \.\.\.region, maturity: "resolved"/);
  assert.match(route, /designRegionTerritoryFailures/);
  assert.match(route, /Compiler-owned canonical rail furniture is not a creative opportunity/);
  assert.match(route, /use its exact grounded identity handle as an identity-mark analysis copy at least once/);
  assert.match(route, /SOURCE_AUTHOR_SCHEMA/);
  assert.match(route, /SOURCE_AUTHOR_SYSTEM/);
  assert.match(route, /Return only decision, moveKind, summary, expectedVisualResult, and patch/);
  assert.match(route, /anyOf:/);
  assert.match(route, /maxOutputTokens: 12_000/);
  assert.match(route, /temperature: 0\.44/);
  assert.match(route, /compileSourceAuthorDecision/);
  assert.match(route, /compileCanvasV2CompositionState/);
  assert.match(route, /firstRailDetailPerLane/);
  assert.match(route, /canvasV2DesignModelChain\(modelSelection\)/);
  assert.match(route, /lateStageConvergence/);
  assert.match(route, /new evidence-relative island is justified only/);
  assert.match(route, /The supplied convergencePhase is deliberate orchestration, not a turn cap/);
  assert.match(route, /reasoningEffort: "low"/);
  assert.match(route, /CREATIVE_DIRECTOR_SYSTEM/);
  assert.match(route, /creativeBriefSchemaForRevision/);
  assert.match(route, /evidenceHandle: \{ type: "string", enum: evidenceHandles \}/);
  assert.match(route, /anchorNodeId: \{ type: "string", enum: anchorNodeIds/);
  assert.match(route, /creativeCheckpointBrief/);
  assert.match(route, /maxOutputTokens: 8_000/);
  assert.match(route, /reasoningEffort: "medium"/);
  assert.match(route, /models: modelChain/);
  assert.match(route, /buildCanvasV2StructuredProviderRequest/);
  assert.doesNotMatch(route, /FOUNDATION_MODEL|CREATIVE_TERTIARY_MODEL|TERTIARY_MODEL/);
  assert.match(route, /const creativeDirectionTurn = synthesisTurn/);
  assert.match(route, /evidenceSelections/);
  assert.match(route, /scaleIntent/);
  assert.match(route, /Do not author page-dominating screenshots/);
  assert.match(route, /preservedStrengths/);
  assert.match(route, /regressionRisk/);
  assert.match(route, /preservation contract/);
  assert.match(route, /whole-board placement/);
  assert.match(route, /evidence-relative-island/);
  assert.match(route, /data-canvas-v2-placement-mode/);
  assert.match(route, /data-canvas-v2-target-zone/);
  assert.match(route, /targetZoneId/);
  assert.match(route, /nextTerritory/);
  assert.match(route, /validateCanvasV2DecisionComposition/);
  assert.match(route, /authoredVisualRoles/);
  assert.doesNotMatch(route, /evidenceId: evidenceId\.slice/);
  assert.match(route, /data-canvas-v2-visual-role/);
  assert.match(route, /data-canvas-v2-copy-evidence-handle/);
  assert.match(route, /data-canvas-v2-annotation-for/);
  assert.match(route, /data-canvas-v2-relationship-source/);
  assert.match(route, /validateCanvasV2RenderedAnalysisEvidenceScale/);
  assert.match(route, /validateCanvasV2RenderedComparisonCommunication/);
  assert.match(route, /validateCanvasV2RenderedRelationshipGeometry/);
  assert.match(grammar, /Inline SVG is available for model-authored relationship geometry/);
  assert.match(grammar, /Never let two unannotated phone screens swallow the synthesis/);
  assert.match(grammar, /Side-by-side prose with decorative thumbnails is scaffolding/);
  assert.match(route, /Treat connectors and other endpoint-dependent geometry as an integration layer, not an early scaffold/);
  assert.match(route, /Do not introduce SVG relationship geometry while the composition is still a scaffold/);
  assert.match(route, /permanently reserved as framing/);
  assert.match(route, /cannot absorb screenshot-led comparison or analysis/);
  assert.match(route, /Do not open another island while authored work remains unfinished/);
  assert.match(route, /replace or update all affected geometry in the same patch/);
  assert.match(grammar, /SVG is not mandatory/);
  assert.match(grammar, /rebuild every affected path in that same edit/);
  assert.match(route, /validateCanvasV2CreativeBriefExecution/);
  assert.match(route, /validateCanvasV2AnalysisEvidenceContinuity/);
  assert.match(route, /focused evidence selection list of no more than eight items/);
  assert.match(route, /authoredVisualRoles\.some/);
  assert.doesNotMatch(route, /slice\(0, 4\)\.flatMap/);
});

test("the visible proof develops a composition across research, framing, analysis, and refinement", () => {
  const fixture = readFileSync("app/canvas-v2-e2e/design/route.ts", "utf8");
  assert.match(fixture, /moveKind: "research"/);
  assert.match(fixture, /moveKind: "framing"/);
  assert.match(fixture, /moveKind: "composition"/);
  assert.match(fixture, /moveKind: "analysis"/);
  assert.match(fixture, /moveKind: "refinement"/);
  assert.match(fixture, /Executive implication/);
  assert.doesNotMatch(fixture, /class="[^"]*card/);
});
