import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("the model owns an evolving creative direction rather than a runtime aesthetic score", () => {
  const types = readFileSync("lib/canvas-v2/types.ts", "utf8");
  const route = readFileSync("app/api/canvas-v2/design/route.ts", "utf8");
  const loop = readFileSync("lib/canvas-v2/design-loop.ts", "utf8");

  assert.match(types, /interface CanvasV2CreativeDirection/);
  assert.match(types, /interface CanvasV2RenderedReflection/);
  assert.match(types, /unresolvedOpportunities: string\[\]/);
  for (const read of ["conceptRead", "hierarchyRead", "evidenceRead", "relationshipRead", "legibilityRead", "distinctivenessRead"]) {
    assert.match(types, new RegExp(`${read}: string`));
  }
  assert.match(route, /visual director/);
  assert.match(route, /preserve them as an explicit preservation contract/);
  assert.match(route, /server owns those responsibilities/);
  assert.match(loop, /creativeDirection: input\.creativeDirection/);
  assert.doesNotMatch(`${types}\n${loop}`, /aestheticScore|visualScore|scoreThreshold/);
});

test("creative moves are purposeful and remain open to divergent visual forms", () => {
  const route = readFileSync("app/api/canvas-v2/design/route.ts", "utf8");
  const grammar = readFileSync("lib/canvas-v2/northstar-canvas-grammar.ts", "utf8");

  for (const move of ["framing", "composition", "relationship", "analysis", "refinement"]) {
    assert.match(route, new RegExp(`\\"${move}\\"`));
  }
  assert.match(route, /original hybrid/);
  assert.match(route, /never prescribed templates/);
  assert.match(grammar, /editorial intelligence/);
  assert.match(grammar, /artifact-scoped CSS with custom properties/);
  assert.match(grammar, /Avoid returning the same header-plus-cards composition/);
  assert.match(grammar, /complete-canvas overview as a first-class reading distance/);
  assert.match(grammar, /straight connectors, directional arrows, and fluid curves/);
  assert.match(grammar, /violet\/blue is iconic and available, not a mandatory default/i);
  assert.match(grammar, /one accent, a tonal family, or several contrasting colors/i);
  assert.match(grammar, /Do not repeatedly color titles pale blue or violet/i);
  assert.match(route, /Progressive judgment without a creative-turn ceiling/);
  assert.match(route, /North Star visual-language references/);
  assert.match(route, /strategic-storyline-atlas\.png/);
  assert.match(route, /evidence-constellation\.png/);
  assert.match(route, /quick-visible-foundation/);
  assert.match(route, /progressive-visible-development/);
  assert.match(route, /phase: "integration"/);
  assert.match(route, /phase: "convergence"/);
  assert.match(route, /phase: "final-review"/);
  assert.match(route, /observedDesignTurns < 15/);
  assert.match(route, /observedDesignTurns < 18/);
  assert.match(route, /Every visible synthesis turn starts with a compact whole-board judgment/);
  assert.match(route, /repeatedLocalWork/);
  assert.match(route, /REPETITION_GENERIC_MOVE_TERMS/);
  assert.match(route, /sharedDistinctiveMoveTerms/);
  assert.match(route, /must compare the authored device, not the vocabulary/);
  assert.match(route, /REPETITION REDIRECTION/);
  assert.match(route, /PHASE AUTHORITY/);
  assert.match(route, /Do not recommend completion/);
  assert.match(route, /Zones already carrying authored design regions/);
  assert.match(route, /maxInvalidResponsesPerModel: 4/);
  assert.match(route, /do not emit a no-op CSS patch, continuity edit, or speculative polish turn/);
  assert.match(route, /A visible design turn must make one material rendered change/);
  assert.match(route, /directorCompletionDecision/);
  assert.match(route, /creativeCheckpointBrief\?\.completionRecommendation === "complete"/);
  assert.match(route, /deterministic completion checks found a concrete visible omission/);
  assert.match(route, /missingIdentitySelections/);
  assert.match(route, /completion-integrity-repair/);
  assert.match(route, /validator-required completion repair/);
  assert.match(route, /rename or repeat that repair under another move kind/);
  assert.match(route, /Convergence is part of visual judgment/);
  assert.match(route, /repeatedPair \|\| repeatedSequence/);
  assert.match(route, /Do not rename or repeat that repair/);
  assert.match(route, /Repetition and diminishing returns are visual-direction context/);
  assert.match(route, /targetIsland/);
  assert.match(route, /buildCanvasV2IslandRegistry/);
  assert.match(route, /islandRegistry\.length === 0/);
  assert.match(route, /canvasV2AllocatedIslandId/);
  assert.match(route, /focusedIslandSource/);
  assert.match(route, /compactCanvasV2IslandSourceForModel/);
  assert.match(route, /newlyRequiredEvidenceIds/);
  assert.match(route, /missingAfterPatch/);
  assert.match(route, /bindCanvasV2SelectedEvidenceToExistingIsland/);
  assert.match(route, /Existing island \$\{targetId\} is durable/);
  assert.match(route, /Never remove or replace its top-level node/);
  assert.match(route, /Focused target-island capture/);
  assert.match(route, /Create must target the exact server-allocated island identity/);
  assert.match(route, /develop, enrich, or repair, choose an exact existing island ID/);
  assert.match(route, /resultingMaturity/);
  assert.match(route, /openRequirements/);
  assert.match(route, /Never use whole-board completion to fabricate resolved island state/);
  assert.match(route, /Whole-board completion is blocked by unfinished island lifecycle state/);
  assert.match(route, /brief\.completionRecommendation === "complete" && unfinishedIsland/);
  assert.match(route, /next visible turn must finish it before whole-board completion/);
  assert.doesNotMatch(route, /regions: input\.compositionState\.regions\.map\(\(region\) => \(\{ \.\.\.region, maturity: "resolved"/);
  assert.match(route, /designRegionTerritoryFailures/);
  assert.match(route, /designRegionLegibilityFailures/);
  assert.match(route, /later island may never look like compressed debug output/);
  assert.match(route, /Headings must render at least 40 canvas pixels/);
  assert.match(route, /Compiler-owned canonical rail furniture is not a creative opportunity/);
  assert.match(route, /use its exact grounded identity handle as an identity-mark analysis copy at least once/);
  assert.match(route, /SOURCE_AUTHOR_SCHEMA/);
  assert.match(route, /SOURCE_AUTHOR_SYSTEM/);
  assert.match(route, /Return only decision, moveKind, summary, expectedVisualResult, and patch/);
  assert.match(route, /anyOf:/);
  assert.match(route, /maxOutputTokens: 12_000/);
  assert.match(route, /temperature: 0\.44/);
  assert.match(route, /compileSourceAuthorDecision/);
  assert.match(route, /compileCanvasV2CompositionState/);
  assert.match(route, /firstRailDetailPerLane/);
  assert.match(route, /canvasV2DesignModelChain\(modelSelection\)/);
  assert.match(route, /lateStageConvergence/);
  assert.match(route, /new evidence-relative island is justified only/);
  assert.match(route, /The supplied convergencePhase is deliberate orchestration, not a turn cap/);
  assert.match(route, /acceptedWholeBoardRecompositions/);
  assert.match(route, /instead of opening another speculative polish turn/);
  assert.match(route, /finite world is navigation capacity, not a target publication footprint/);
  assert.match(route, /relationship geometry is optional, never a box to tick/i);
  assert.match(route, /canvasV2InstructionExplicitlyRequestsRelationshipGeometry/);
  assert.match(route, /cannot become an island finishing obligation/);
  assert.match(route, /Do not add optional connector or endpoint-dependent relationship geometry as a new finishing pass/);
  assert.match(route, /relationship geometry remains an optional model-chosen device, not a completion requirement/i);
  assert.match(route, /completionSummary/);
  assert.match(route, /final handoff to the person who asked for the work/);
  assert.match(route, /summary: input\.brief\.completionSummary/);
  assert.match(route, /userFacingCompletionSummary/);
  assert.match(route, /COMPLETION_SUMMARY_INTERNAL_JARGON/);
  assert.match(route, /canvas remains fully editable/);
  assert.match(route, /observedDesignTurns >= 2/);
  assert.match(route, /One visible design turn is one bounded material move/);
  assert.match(route, /creating endpoints and integrating their connector system are two separate material moves/);
  assert.match(route, /explicitly requested a relationship-led composition/);
  assert.match(route, /EXACT HUMAN RELATIONSHIP REFINEMENT/);
  assert.match(route, /explicitRelationshipRefinementRequested/);
  assert.match(route, /explicitRelationshipRefinementRequested = turn === 1/);
  assert.match(route, /do not replace the requested edit with a completion-only response/);
  assert.match(route, /resolvedStory\s*&& repeatedLocalWork/);
  assert.match(route, /Recommend completion now instead of reopening that visual detail under new wording/);
  assert.match(route, /explicitWholeBoardRecompositionRequested/);
  assert.match(route, /Do not risk a speculative whole-board recompose/);
  assert.match(route, /an optional alternative layout is not a completion blocker/);
  assert.match(route, /Inspect the actual pixels, not merely the ledger/);
  assert.match(route, /Repetition must earn its place/);
  assert.match(route, /Multi-line type needs honest leading/);
  assert.match(route, /hidden horizontal artboard and collapses earlier content into sliver columns/);
  assert.match(route, /repeatedResolvedIslandRefinement/);
  assert.match(route, /two consecutive bounded refinements and no objective blocker remains/);
  assert.match(route, /const resolvedStory = titleIslands\.length === 1/);
  assert.match(route, /promptCoverageFailures\.length === 0/);
  assert.match(route, /validateCanvasV2RequestedCompositionCoverage/);
  assert.match(route, /A title, subtitle, orientation paragraph, or roadmap promise/);
  assert.match(route, /resolvedStory \? "final-review"/);
  assert.match(route, /reasoningEffort: "low"/);
  assert.match(route, /CREATIVE_DIRECTOR_SYSTEM/);
  assert.match(route, /creativeBriefSchemaForRevision/);
  assert.match(route, /evidenceHandle: \{ type: "string", enum: evidenceHandles \}/);
  assert.match(route, /anchorNodeId: \{ type: "string", enum: anchorNodeIds/);
  assert.match(route, /creativeCheckpointBrief/);
  assert.match(route, /maxOutputTokens: 8_000/);
  assert.match(route, /reasoningEffort: "medium"/);
  assert.match(route, /models: modelChain/);
  assert.match(route, /buildCanvasV2StructuredProviderRequest/);
  assert.doesNotMatch(route, /FOUNDATION_MODEL|CREATIVE_TERTIARY_MODEL|TERTIARY_MODEL/);
  assert.match(route, /const synthesisTurn = researchMode !== "evidence"/);
  assert.match(route, /const creativeDirectionTurn = synthesisTurn/);
  assert.match(route, /evidenceSelections/);
  assert.match(route, /scaleIntent/);
  assert.match(route, /Do not author page-dominating screenshots/);
  assert.match(route, /preservedStrengths/);
  assert.match(route, /regressionRisk/);
  assert.match(route, /preservation contract/);
  assert.match(route, /whole-board placement/);
  assert.match(route, /Ordinary consecutive chapters must remain in close visual proximity/);
  assert.match(route, /15–25% working zoom/);
  assert.match(route, /within 1,200px of its preceding narrative neighbor/);
  assert.match(route, /evidence-relative-island/);
  assert.match(route, /data-canvas-v2-placement-mode/);
  assert.match(route, /data-canvas-v2-target-zone/);
  assert.match(route, /data-canvas-v2-territory-anchor/);
  assert.match(route, /compactCanvasV2NewIslandPlacement/);
  assert.match(route, /Creation is one atomic island transaction/);
  assert.match(route, /global prompt-coverage ledger decides which independent island comes next/);
  assert.match(route, /Preserve the same compiler-owned execution contract that passed/);
  assert.match(route, /targetZoneId/);
  assert.match(route, /nextTerritory/);
  assert.match(route, /validateCanvasV2DecisionComposition/);
  assert.match(route, /authoredVisualRoles/);
  assert.doesNotMatch(route, /evidenceId: evidenceId\.slice/);
  assert.match(route, /data-canvas-v2-visual-role/);
  assert.match(route, /data-canvas-v2-copy-evidence-handle/);
  assert.match(route, /data-canvas-v2-annotation-for/);
  assert.match(route, /data-canvas-v2-relationship-source/);
  assert.match(route, /validateCanvasV2RenderedAnalysisEvidenceScale/);
  assert.match(route, /validateCanvasV2RenderedComparisonCommunication/);
  assert.match(route, /validateCanvasV2RenderedRelationshipGeometry/);
  assert.match(grammar, /Inline SVG is available for model-authored relationship geometry/);
  assert.match(grammar, /Never let two unannotated phone screens swallow the synthesis/);
  assert.match(grammar, /Side-by-side prose with decorative thumbnails is scaffolding/);
  assert.match(route, /Treat connectors and other endpoint-dependent geometry as an integration layer, not an early scaffold/);
  assert.match(route, /Do not introduce SVG relationship geometry while the composition is still a scaffold/);
  assert.match(route, /permanently reserved as framing/);
  assert.match(route, /cannot absorb screenshot-led comparison or analysis/);
  assert.match(route, /Do not open another island while authored work remains unfinished/);
  assert.match(route, /replace or update all affected geometry in the same patch/);
  assert.match(grammar, /SVG is not mandatory/);
  assert.match(grammar, /rebuild every affected path in that same edit/);
  assert.match(route, /validateCanvasV2CreativeBriefExecution/);
  assert.match(route, /validateCanvasV2AnalysisEvidenceContinuity/);
  assert.match(route, /focused evidence selection list of no more than eight items/);
  assert.match(route, /authoredVisualRoles\.some/);
  assert.doesNotMatch(route, /slice\(0, 4\)\.flatMap/);
});

test("the visible proof develops a composition across research, framing, analysis, and refinement", () => {
  const fixture = readFileSync("app/canvas-v2-e2e/design/route.ts", "utf8");
  assert.match(fixture, /moveKind: "research"/);
  assert.match(fixture, /moveKind: "framing"/);
  assert.match(fixture, /moveKind: "composition"/);
  assert.match(fixture, /moveKind: "analysis"/);
  assert.match(fixture, /moveKind: "refinement"/);
  assert.match(fixture, /Executive implication/);
  assert.doesNotMatch(fixture, /class="[^"]*card/);
});
