import {
  assertValidNorthstarLedgerValue,
  cloneNorthstarLedgerValue,
} from "@/lib/canvas-ledger/northstar-ledger-value";
import type {
  NorthstarActivityDraft,
  NorthstarLedgerCommit,
  NorthstarLedgerEvent,
  NorthstarLedgerFailure,
  NorthstarLedgerLLMContext,
  NorthstarLedgerTask,
  NorthstarLedgerTaskAttempt,
  NorthstarLedgerValue,
  NorthstarProjectionReceipt,
} from "@/lib/canvas-ledger/types";
import {
  NORTHSTAR_TURN_MAX_PAYLOAD_CHARACTERS,
  NORTHSTAR_TURN_PROTOCOL_VERSION,
  type NorthstarAttemptFailureResponse,
  type NorthstarAttemptResultKind,
  type NorthstarAttemptResultResponse,
  type NorthstarCorrectActiveTaskRequest,
  type NorthstarDecideNextActivityRequest,
  type NorthstarExecuteTaskAttemptRequest,
  type NorthstarFinalizeRunRequest,
  type NorthstarTaskCorrectionResponse,
  type NorthstarTurnErrorResponse,
  type NorthstarTurnRequest,
  type NorthstarTurnResponse,
} from "@/lib/canvas-ai/northstar-turn-protocol";

export class NorthstarTurnValidationError extends TypeError {
  readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = "NorthstarTurnValidationError";
    this.code = code;
  }
}

function fail(code: string, message: string): never {
  throw new NorthstarTurnValidationError(code, message);
}

function structuralJSON(value: unknown): string {
  return JSON.stringify(value);
}

const FORBIDDEN_MODEL_IDENTITY_KEYS = new Set([
  "runId",
  "taskId",
  "attemptId",
  "commitHash",
  "candidateCommitHash",
  "candidateStateHash",
  "projectionReceipt",
  "taskSequence",
  "attemptNumber",
  "commitSequence",
]);

export function assertNoNorthstarSystemIdentity(
  value: NorthstarLedgerValue,
  path = "$",
): void {
  if (Array.isArray(value)) {
    value.forEach((entry, index) => assertNoNorthstarSystemIdentity(entry, `${path}[${index}]`));
    return;
  }
  if (value !== null && typeof value === "object") {
    for (const [key, entry] of Object.entries(value)) {
      if (FORBIDDEN_MODEL_IDENTITY_KEYS.has(key)) {
        fail("MODEL_SYSTEM_IDENTITY_FORBIDDEN", `${path}.${key} is owned by the ledger and cannot be generated by the model.`);
      }
      assertNoNorthstarSystemIdentity(entry, `${path}.${key}`);
    }
  }
}

function record(value: unknown, path: string): Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return fail("INVALID_OBJECT", `${path} must be an object.`);
  }
  const prototype = Object.getPrototypeOf(value);
  if (prototype !== Object.prototype && prototype !== null) {
    return fail("INVALID_OBJECT", `${path} must be a plain object.`);
  }
  return value as Record<string, unknown>;
}

function exactKeys(
  value: Record<string, unknown>,
  required: readonly string[],
  optional: readonly string[],
  path: string,
): void {
  const requiredSet = new Set(required);
  const allowed = new Set([...required, ...optional]);
  for (const key of required) {
    if (!Object.prototype.hasOwnProperty.call(value, key)) {
      fail("MISSING_FIELD", `${path}.${key} is required.`);
    }
  }
  for (const key of Object.keys(value)) {
    if (!allowed.has(key)) fail("UNKNOWN_FIELD", `${path}.${key} is not allowed.`);
  }
  for (const key of requiredSet) {
    if (value[key] === undefined) fail("MISSING_FIELD", `${path}.${key} is required.`);
  }
}

function stringValue(value: unknown, path: string, options?: { min?: number; max?: number }): string {
  if (typeof value !== "string") fail("INVALID_STRING", `${path} must be a string.`);
  const min = options?.min ?? 1;
  const max = options?.max ?? 100_000;
  if (value.length < min || value.length > max) {
    fail("INVALID_STRING_LENGTH", `${path} must contain between ${min} and ${max} characters.`);
  }
  return value;
}

function optionalString(value: unknown, path: string): string | undefined {
  if (value === undefined) return undefined;
  return stringValue(value, path);
}

function finiteNumber(value: unknown, path: string, options?: { integer?: boolean; min?: number; max?: number }): number {
  if (typeof value !== "number" || !Number.isFinite(value)) {
    fail("INVALID_NUMBER", `${path} must be a finite number.`);
  }
  if (options?.integer && !Number.isInteger(value)) fail("INVALID_NUMBER", `${path} must be an integer.`);
  if (options?.min !== undefined && value < options.min) fail("INVALID_NUMBER", `${path} must be at least ${options.min}.`);
  if (options?.max !== undefined && value > options.max) fail("INVALID_NUMBER", `${path} must be at most ${options.max}.`);
  return Object.is(value, -0) ? 0 : value;
}

function booleanValue(value: unknown, path: string): boolean {
  if (typeof value !== "boolean") fail("INVALID_BOOLEAN", `${path} must be a boolean.`);
  return value;
}

function enumValue<T extends string>(value: unknown, choices: readonly T[], path: string): T {
  if (typeof value !== "string" || !choices.includes(value as T)) {
    fail("INVALID_ENUM", `${path} must be one of ${choices.join(", ")}.`);
  }
  return value as T;
}

function ledgerValue(value: unknown, path: string): NorthstarLedgerValue {
  try {
    assertValidNorthstarLedgerValue(value, path);
    return cloneNorthstarLedgerValue(value);
  } catch (error) {
    fail(
      "INVALID_LEDGER_VALUE",
      error instanceof Error ? error.message : `${path} is not a valid ledger value.`,
    );
  }
}

function optionalLedgerValue(value: unknown, path: string): NorthstarLedgerValue | undefined {
  return value === undefined ? undefined : ledgerValue(value, path);
}

function arrayValue<T>(value: unknown, path: string, parser: (entry: unknown, entryPath: string) => T): T[] {
  if (!Array.isArray(value)) fail("INVALID_ARRAY", `${path} must be an array.`);
  return value.map((entry, index) => parser(entry, `${path}[${index}]`));
}

function parseFailure(value: unknown, path: string): NorthstarLedgerFailure {
  const input = record(value, path);
  exactKeys(input, ["kind", "code", "detail", "phase"], ["correctionContext"], path);
  return {
    kind: enumValue(input.kind, ["transient", "correctable", "terminal"] as const, `${path}.kind`),
    code: stringValue(input.code, `${path}.code`, { max: 200 }),
    detail: stringValue(input.detail, `${path}.detail`, { max: 20_000 }),
    phase: enumValue(
      input.phase,
      ["decision", "execution", "preparation", "projection", "control"] as const,
      `${path}.phase`,
    ),
    correctionContext: optionalLedgerValue(input.correctionContext, `${path}.correctionContext`),
  };
}

function parseProjectionReceipt(value: unknown, path: string): NorthstarProjectionReceipt {
  const input = record(value, path);
  exactKeys(
    input,
    ["commitHash", "projectedStateHash", "surfaceSessionId", "verified", "projectedAt"],
    ["metadata"],
    path,
  );
  return {
    commitHash: stringValue(input.commitHash, `${path}.commitHash`, { max: 256 }),
    projectedStateHash: stringValue(input.projectedStateHash, `${path}.projectedStateHash`, { max: 256 }),
    surfaceSessionId: stringValue(input.surfaceSessionId, `${path}.surfaceSessionId`, { max: 256 }),
    verified: booleanValue(input.verified, `${path}.verified`),
    projectedAt: finiteNumber(input.projectedAt, `${path}.projectedAt`),
    metadata: optionalLedgerValue(input.metadata, `${path}.metadata`),
  };
}

const TASK_KINDS = ["research", "analysis", "artboard-mutation", "verification", "finalization"] as const;
const TASK_STATUSES = [
  "created",
  "active",
  "awaiting-preparation",
  "awaiting-projection",
  "awaiting-transport-resolution",
  "retryable-failure",
  "blocked",
  "completed",
  "cancelled",
  "superseded",
] as const;
const ATTEMPT_STATUSES = ["active", "transport-uncertain", "drafted", "prepared", "failed", "cancelled", "completed"] as const;

function parseTask(value: unknown, path: string): NorthstarLedgerTask {
  const input = record(value, path);
  exactKeys(
    input,
    [
      "id",
      "runId",
      "sequence",
      "kind",
      "intent",
      "expectedOutcome",
      "initialExecutionInput",
      "status",
      "baseCommitHash",
      "currentAttemptId",
      "createdAt",
    ],
    ["resultCommitHash", "completedAt", "cancelledAt", "supersededAt"],
    path,
  );
  return {
    id: stringValue(input.id, `${path}.id`, { max: 256 }),
    runId: stringValue(input.runId, `${path}.runId`, { max: 256 }),
    sequence: finiteNumber(input.sequence, `${path}.sequence`, { integer: true, min: 1 }),
    kind: enumValue(input.kind, TASK_KINDS, `${path}.kind`),
    intent: stringValue(input.intent, `${path}.intent`, { max: 20_000 }),
    expectedOutcome: stringValue(input.expectedOutcome, `${path}.expectedOutcome`, { max: 20_000 }),
    initialExecutionInput: ledgerValue(input.initialExecutionInput, `${path}.initialExecutionInput`),
    status: enumValue(input.status, TASK_STATUSES, `${path}.status`),
    baseCommitHash: stringValue(input.baseCommitHash, `${path}.baseCommitHash`, { max: 256 }),
    currentAttemptId: input.currentAttemptId === null
      ? null
      : stringValue(input.currentAttemptId, `${path}.currentAttemptId`, { max: 256 }),
    resultCommitHash: optionalString(input.resultCommitHash, `${path}.resultCommitHash`),
    createdAt: finiteNumber(input.createdAt, `${path}.createdAt`),
    completedAt: input.completedAt === undefined ? undefined : finiteNumber(input.completedAt, `${path}.completedAt`),
    cancelledAt: input.cancelledAt === undefined ? undefined : finiteNumber(input.cancelledAt, `${path}.cancelledAt`),
    supersededAt: input.supersededAt === undefined ? undefined : finiteNumber(input.supersededAt, `${path}.supersededAt`),
  };
}

function parseTransportUncertainty(value: unknown, path: string) {
  const input = record(value, path);
  exactKeys(
    input,
    [
      "requestId",
      "code",
      "detail",
      "retryable",
      "deliveryAttempts",
      "firstObservedAt",
      "lastObservedAt",
    ],
    [],
    path,
  );
  return {
    requestId: stringValue(input.requestId, `${path}.requestId`, { min: 8, max: 128 }),
    code: stringValue(input.code, `${path}.code`, { max: 200 }),
    detail: stringValue(input.detail, `${path}.detail`, { max: 20_000 }),
    retryable: booleanValue(input.retryable, `${path}.retryable`),
    deliveryAttempts: finiteNumber(input.deliveryAttempts, `${path}.deliveryAttempts`, { integer: true, min: 1 }),
    firstObservedAt: finiteNumber(input.firstObservedAt, `${path}.firstObservedAt`),
    lastObservedAt: finiteNumber(input.lastObservedAt, `${path}.lastObservedAt`),
  };
}

function parseAttempt(value: unknown, path: string): NorthstarLedgerTaskAttempt {
  const input = record(value, path);
  exactKeys(
    input,
    ["id", "runId", "taskId", "attemptNumber", "executionInput", "status", "startedAt"],
    [
      "preparedResult",
      "evidence",
      "candidateCommitHash",
      "candidateStateHash",
      "result",
      "stateSnapshot",
      "projectionReceipt",
      "transportUncertainty",
      "preparationFailures",
      "projectionFailures",
      "failure",
      "draftedAt",
      "preparedAt",
      "completedAt",
    ],
    path,
  );
  return {
    id: stringValue(input.id, `${path}.id`, { max: 256 }),
    runId: stringValue(input.runId, `${path}.runId`, { max: 256 }),
    taskId: stringValue(input.taskId, `${path}.taskId`, { max: 256 }),
    attemptNumber: finiteNumber(input.attemptNumber, `${path}.attemptNumber`, { integer: true, min: 1 }),
    executionInput: ledgerValue(input.executionInput, `${path}.executionInput`),
    status: enumValue(input.status, ATTEMPT_STATUSES, `${path}.status`),
    preparedResult: optionalLedgerValue(input.preparedResult, `${path}.preparedResult`),
    evidence: optionalLedgerValue(input.evidence, `${path}.evidence`),
    candidateCommitHash: optionalString(input.candidateCommitHash, `${path}.candidateCommitHash`),
    candidateStateHash: optionalString(input.candidateStateHash, `${path}.candidateStateHash`),
    result: optionalLedgerValue(input.result, `${path}.result`),
    stateSnapshot: optionalLedgerValue(input.stateSnapshot, `${path}.stateSnapshot`),
    projectionReceipt: input.projectionReceipt === undefined
      ? undefined
      : parseProjectionReceipt(input.projectionReceipt, `${path}.projectionReceipt`),
    transportUncertainty: input.transportUncertainty === undefined
      ? undefined
      : parseTransportUncertainty(input.transportUncertainty, `${path}.transportUncertainty`),
    preparationFailures: input.preparationFailures === undefined
      ? undefined
      : arrayValue(input.preparationFailures, `${path}.preparationFailures`, parseFailure),
    projectionFailures: input.projectionFailures === undefined
      ? undefined
      : arrayValue(input.projectionFailures, `${path}.projectionFailures`, parseFailure),
    failure: input.failure === undefined ? undefined : parseFailure(input.failure, `${path}.failure`),
    startedAt: finiteNumber(input.startedAt, `${path}.startedAt`),
    draftedAt: input.draftedAt === undefined ? undefined : finiteNumber(input.draftedAt, `${path}.draftedAt`),
    preparedAt: input.preparedAt === undefined ? undefined : finiteNumber(input.preparedAt, `${path}.preparedAt`),
    completedAt: input.completedAt === undefined ? undefined : finiteNumber(input.completedAt, `${path}.completedAt`),
  };
}

function parseCommit(value: unknown, path: string): NorthstarLedgerCommit {
  const input = record(value, path);
  exactKeys(
    input,
    [
      "hash",
      "stateHash",
      "runId",
      "sequence",
      "kind",
      "parentHash",
      "taskId",
      "attemptId",
      "taskKind",
      "result",
      "stateSnapshot",
      "createdAt",
    ],
    ["projectionReceipt"],
    path,
  );
  return {
    hash: stringValue(input.hash, `${path}.hash`, { max: 256 }),
    stateHash: stringValue(input.stateHash, `${path}.stateHash`, { max: 256 }),
    runId: stringValue(input.runId, `${path}.runId`, { max: 256 }),
    sequence: finiteNumber(input.sequence, `${path}.sequence`, { integer: true, min: 0 }),
    kind: enumValue(input.kind, ["root", "task"] as const, `${path}.kind`),
    parentHash: input.parentHash === null ? null : stringValue(input.parentHash, `${path}.parentHash`, { max: 256 }),
    taskId: input.taskId === null ? null : stringValue(input.taskId, `${path}.taskId`, { max: 256 }),
    attemptId: input.attemptId === null ? null : stringValue(input.attemptId, `${path}.attemptId`, { max: 256 }),
    taskKind: input.taskKind === null ? null : enumValue(input.taskKind, TASK_KINDS, `${path}.taskKind`),
    result: ledgerValue(input.result, `${path}.result`),
    stateSnapshot: ledgerValue(input.stateSnapshot, `${path}.stateSnapshot`),
    projectionReceipt: input.projectionReceipt === undefined
      ? undefined
      : parseProjectionReceipt(input.projectionReceipt, `${path}.projectionReceipt`),
    createdAt: finiteNumber(input.createdAt, `${path}.createdAt`),
  };
}

function parseEvent(value: unknown, path: string): NorthstarLedgerEvent {
  const input = record(value, path);
  exactKeys(
    input,
    ["sequence", "runId", "type", "summary", "timestamp"],
    ["taskId", "attemptId", "commitHash", "payload"],
    path,
  );
  return {
    sequence: finiteNumber(input.sequence, `${path}.sequence`, { integer: true, min: 1 }),
    runId: stringValue(input.runId, `${path}.runId`, { max: 256 }),
    taskId: optionalString(input.taskId, `${path}.taskId`),
    attemptId: optionalString(input.attemptId, `${path}.attemptId`),
    commitHash: optionalString(input.commitHash, `${path}.commitHash`),
    type: enumValue(
      input.type,
      [
        "run.created",
        "run.completed",
        "run.failed",
        "decision.recorded",
        "control.failed",
        "task.created",
        "task.cancelled",
        "task.superseded",
        "attempt.started",
        "attempt.drafted",
        "attempt.prepared",
        "attempt.failed",
        "attempt.transport-uncertain",
        "attempt.transport-retrying",
        "projection.retrying",
        "projection.failed",
        "commit.created",
        "task.completed",
      ] as const,
      `${path}.type`,
    ),
    summary: stringValue(input.summary, `${path}.summary`, { max: 20_000 }),
    payload: optionalLedgerValue(input.payload, `${path}.payload`),
    timestamp: finiteNumber(input.timestamp, `${path}.timestamp`),
  };
}

export function parseNorthstarLedgerLLMContext(value: unknown, path = "$.ledgerContext"): NorthstarLedgerLLMContext {
  const input = record(value, path);
  exactKeys(
    input,
    ["schema", "run", "currentHead", "activeTask", "tasks", "attempts", "commits", "events", "outstandingObligations"],
    [],
    path,
  );
  if (input.schema !== "northstar.ledger-context.v1") {
    fail("INVALID_CONTEXT_SCHEMA", `${path}.schema must be northstar.ledger-context.v1.`);
  }

  const runInput = record(input.run, `${path}.run`);
  exactKeys(runInput, ["id", "objective", "status", "createdAt"], [], `${path}.run`);
  const run = {
    id: stringValue(runInput.id, `${path}.run.id`, { max: 256 }),
    objective: stringValue(runInput.objective, `${path}.run.objective`, { max: 100_000 }),
    status: enumValue(runInput.status, ["active", "completed", "failed", "cancelled"] as const, `${path}.run.status`),
    createdAt: finiteNumber(runInput.createdAt, `${path}.run.createdAt`),
  };

  const headInput = record(input.currentHead, `${path}.currentHead`);
  exactKeys(headInput, ["hash", "stateHash", "sequence", "stateSnapshot"], [], `${path}.currentHead`);
  const currentHead = {
    hash: stringValue(headInput.hash, `${path}.currentHead.hash`, { max: 256 }),
    stateHash: stringValue(headInput.stateHash, `${path}.currentHead.stateHash`, { max: 256 }),
    sequence: finiteNumber(headInput.sequence, `${path}.currentHead.sequence`, { integer: true, min: 0 }),
    stateSnapshot: ledgerValue(headInput.stateSnapshot, `${path}.currentHead.stateSnapshot`),
  };

  const tasks = arrayValue(input.tasks, `${path}.tasks`, parseTask);
  const attempts = arrayValue(input.attempts, `${path}.attempts`, parseAttempt);
  const commits = arrayValue(input.commits, `${path}.commits`, parseCommit);
  const events = arrayValue(input.events, `${path}.events`, parseEvent);
  const outstandingObligations = arrayValue(
    input.outstandingObligations,
    `${path}.outstandingObligations`,
    (entry, entryPath) => stringValue(entry, entryPath, { max: 20_000 }),
  );

  const activeTask = input.activeTask === null
    ? null
    : (() => {
        const activeInput = record(input.activeTask, `${path}.activeTask`);
        exactKeys(activeInput, ["task", "attempts"], [], `${path}.activeTask`);
        return {
          task: parseTask(activeInput.task, `${path}.activeTask.task`),
          attempts: arrayValue(activeInput.attempts, `${path}.activeTask.attempts`, parseAttempt),
        };
      })();

  const taskIds = new Set<string>();
  for (const task of tasks) {
    if (task.runId !== run.id) fail("CONTEXT_RUN_MISMATCH", `Task ${task.id} belongs to another run.`);
    if (taskIds.has(task.id)) fail("DUPLICATE_CONTEXT_ID", `Task ${task.id} appears more than once.`);
    taskIds.add(task.id);
  }
  const attemptIds = new Set<string>();
  for (const attempt of attempts) {
    if (attempt.runId !== run.id || !taskIds.has(attempt.taskId)) {
      fail("CONTEXT_RUN_MISMATCH", `Attempt ${attempt.id} is not attached to this run and task history.`);
    }
    if (attemptIds.has(attempt.id)) fail("DUPLICATE_CONTEXT_ID", `Attempt ${attempt.id} appears more than once.`);
    attemptIds.add(attempt.id);
  }
  if (commits.length === 0) fail("INVALID_CONTEXT_HEAD", "The ledger context must include at least the root commit.");
  const headCommit = commits.find((commit) => commit.hash === currentHead.hash);
  if (!headCommit || headCommit.stateHash !== currentHead.stateHash || headCommit.sequence !== currentHead.sequence) {
    fail("INVALID_CONTEXT_HEAD", "currentHead does not match an included commit.");
  }
  if (structuralJSON(headCommit.stateSnapshot) !== structuralJSON(currentHead.stateSnapshot)) {
    fail("INVALID_CONTEXT_HEAD", "currentHead stateSnapshot does not match the head commit.");
  }

  if (activeTask) {
    const matchingTask = tasks.find((task) => task.id === activeTask.task.id);
    if (!matchingTask || structuralJSON(matchingTask) !== structuralJSON(activeTask.task)) {
      fail("INVALID_ACTIVE_TASK", "activeTask.task must match the task history exactly.");
    }
    const fullTaskAttempts = attempts.filter((attempt) => attempt.taskId === activeTask.task.id);
    if (fullTaskAttempts.length !== activeTask.attempts.length) {
      fail("INVALID_ACTIVE_TASK", "activeTask.attempts must contain the complete attempt history for the active task.");
    }
    for (const attempt of activeTask.attempts) {
      const matchingAttempt = attempts.find((candidate) => candidate.id === attempt.id);
      if (
        !matchingAttempt ||
        attempt.taskId !== activeTask.task.id ||
        structuralJSON(matchingAttempt) !== structuralJSON(attempt)
      ) {
        fail("INVALID_ACTIVE_TASK", `Active attempt ${attempt.id} is inconsistent with the full history.`);
      }
    }
    if (activeTask.task.currentAttemptId && !activeTask.attempts.some((attempt) => attempt.id === activeTask.task.currentAttemptId)) {
      fail("INVALID_ACTIVE_TASK", "The active task currentAttemptId is missing from its attempt history.");
    }
  }

  const unresolvedTasks = tasks.filter((task) => !["completed", "cancelled", "superseded"].includes(task.status));
  if (activeTask === null && unresolvedTasks.length > 0) {
    fail("INVALID_ACTIVE_TASK", "The context hides an unresolved task while activeTask is null.");
  }
  if (activeTask !== null && (unresolvedTasks.length !== 1 || unresolvedTasks[0]?.id !== activeTask.task.id)) {
    fail("INVALID_ACTIVE_TASK", "The context must have exactly one unresolved task and it must be activeTask.");
  }

  const commitHashes = new Set<string>();
  for (const commit of commits) {
    if (commit.runId !== run.id) fail("CONTEXT_RUN_MISMATCH", `Commit ${commit.hash} belongs to another run.`);
    if (commitHashes.has(commit.hash)) fail("DUPLICATE_CONTEXT_ID", `Commit ${commit.hash} appears more than once.`);
    commitHashes.add(commit.hash);
  }
  for (const event of events) {
    if (event.runId !== run.id) fail("CONTEXT_RUN_MISMATCH", `Event ${event.sequence} belongs to another run.`);
  }

  return {
    schema: "northstar.ledger-context.v1",
    run,
    currentHead,
    activeTask,
    tasks,
    attempts,
    commits,
    events,
    outstandingObligations,
  };
}

function parseActivity(value: unknown, path: string): NorthstarActivityDraft {
  const input = record(value, path);
  exactKeys(input, ["kind", "intent", "expectedOutcome", "executionInput"], [], path);
  const kind = enumValue(input.kind, TASK_KINDS, `${path}.kind`);
  if (kind === "finalization") {
    fail("INVALID_ACTIVITY_KIND", "Finalization must use the finalize-run turn, not an activity draft.");
  }
  const executionInput = ledgerValue(input.executionInput, `${path}.executionInput`);
  assertNoNorthstarSystemIdentity(executionInput, `${path}.executionInput`);
  return {
    kind,
    intent: stringValue(input.intent, `${path}.intent`, { max: 20_000 }),
    expectedOutcome: stringValue(input.expectedOutcome, `${path}.expectedOutcome`, { max: 20_000 }),
    executionInput,
  };
}

function validatePayloadSize(value: unknown): void {
  let serialized: string;
  try {
    serialized = JSON.stringify(value);
  } catch {
    fail("INVALID_JSON_VALUE", "The turn payload must be serializable JSON.");
  }
  if (serialized.length > NORTHSTAR_TURN_MAX_PAYLOAD_CHARACTERS) {
    fail("PAYLOAD_TOO_LARGE", `The turn payload exceeds ${NORTHSTAR_TURN_MAX_PAYLOAD_CHARACTERS} characters.`);
  }
}

function requestBase(input: Record<string, unknown>, path: string) {
  if (input.protocolVersion !== NORTHSTAR_TURN_PROTOCOL_VERSION) {
    fail("INVALID_PROTOCOL_VERSION", `${path}.protocolVersion must be ${NORTHSTAR_TURN_PROTOCOL_VERSION}.`);
  }
  const requestId = stringValue(input.requestId, `${path}.requestId`, { min: 8, max: 128 });
  if (!/^[A-Za-z0-9._:-]+$/.test(requestId)) {
    fail("INVALID_REQUEST_ID", `${path}.requestId contains unsupported characters.`);
  }
  return {
    protocolVersion: NORTHSTAR_TURN_PROTOCOL_VERSION,
    requestId,
    ledgerContext: parseNorthstarLedgerLLMContext(input.ledgerContext),
  } as const;
}

function ensureTaskMatchesContext(context: NorthstarLedgerLLMContext, task: NorthstarLedgerTask): void {
  if (!context.activeTask) fail("ACTIVE_TASK_REQUIRED", "This turn requires one active ledger task.");
  if (context.activeTask.task.id !== task.id) fail("STALE_TASK", `Task ${task.id} is not the active task.`);
  if (structuralJSON(context.activeTask.task) !== structuralJSON(task)) {
    fail("STALE_TASK", `Task ${task.id} does not match the authoritative ledger context.`);
  }
}

function ensureAttemptMatchesContext(
  context: NorthstarLedgerLLMContext,
  task: NorthstarLedgerTask,
  attempt: NorthstarLedgerTaskAttempt,
): void {
  ensureTaskMatchesContext(context, task);
  const matching = context.activeTask?.attempts.find((candidate) => candidate.id === attempt.id);
  if (!matching || attempt.taskId !== task.id) fail("STALE_ATTEMPT", `Attempt ${attempt.id} is not active for task ${task.id}.`);
  if (structuralJSON(matching) !== structuralJSON(attempt)) {
    fail("STALE_ATTEMPT", `Attempt ${attempt.id} does not match the authoritative ledger context.`);
  }
}

export function parseNorthstarTurnRequest(value: unknown): NorthstarTurnRequest {
  validatePayloadSize(value);
  const input = record(value, "$" );
  const type = enumValue(
    input.type,
    ["decide-next-activity", "execute-task-attempt", "correct-active-task", "finalize-run"] as const,
    "$.type",
  );

  if (type === "decide-next-activity") {
    exactKeys(input, ["protocolVersion", "requestId", "type", "ledgerContext"], [], "$");
    const base = requestBase(input, "$");
    if (base.ledgerContext.run.status !== "active") fail("RUN_NOT_ACTIVE", "A new decision requires an active run.");
    if (base.ledgerContext.activeTask) fail("UNRESOLVED_TASK", "A new decision cannot be requested while a task is unresolved.");
    return { ...base, type } satisfies NorthstarDecideNextActivityRequest;
  }

  if (type === "execute-task-attempt") {
    exactKeys(input, ["protocolVersion", "requestId", "type", "ledgerContext", "task", "attempt"], [], "$");
    const base = requestBase(input, "$");
    const task = parseTask(input.task, "$.task");
    const attempt = parseAttempt(input.attempt, "$.attempt");
    ensureAttemptMatchesContext(base.ledgerContext, task, attempt);
    const isActiveAttempt = attempt.status === "active";
    const isExactTransportRetry =
      attempt.status === "transport-uncertain" &&
      attempt.transportUncertainty?.requestId === base.requestId &&
      task.status === "awaiting-transport-resolution";
    if ((!isActiveAttempt && !isExactTransportRetry) || task.currentAttemptId !== attempt.id) {
      fail("ATTEMPT_NOT_EXECUTABLE", `Attempt ${attempt.id} is not executable for request ${base.requestId}.`);
    }
    return { ...base, type, task, attempt } satisfies NorthstarExecuteTaskAttemptRequest;
  }

  if (type === "correct-active-task") {
    exactKeys(input, ["protocolVersion", "requestId", "type", "ledgerContext", "task", "latestAttempt"], [], "$");
    const base = requestBase(input, "$");
    const task = parseTask(input.task, "$.task");
    const latestAttempt = parseAttempt(input.latestAttempt, "$.latestAttempt");
    ensureAttemptMatchesContext(base.ledgerContext, task, latestAttempt);
    if (latestAttempt.status !== "failed" || !latestAttempt.failure || latestAttempt.failure.kind !== "correctable") {
      fail("CORRECTION_NOT_ALLOWED", "Correction requires the latest failed correctable attempt.");
    }
    const latestId = base.ledgerContext.activeTask?.attempts.at(-1)?.id;
    if (latestId !== latestAttempt.id) fail("STALE_ATTEMPT", "Correction must target the latest attempt.");
    return { ...base, type, task, latestAttempt } satisfies NorthstarCorrectActiveTaskRequest;
  }

  exactKeys(input, ["protocolVersion", "requestId", "type", "ledgerContext"], [], "$");
  const base = requestBase(input, "$");
  if (base.ledgerContext.run.status !== "active") fail("RUN_NOT_ACTIVE", "Finalization requires an active run.");
  if (base.ledgerContext.activeTask || base.ledgerContext.outstandingObligations.length > 0) {
    fail("FINALIZATION_BLOCKED", "Finalization is not allowed while work remains unresolved.");
  }
  return { ...base, type } satisfies NorthstarFinalizeRunRequest;
}

function expectedResultKind(task: NorthstarLedgerTask): NorthstarAttemptResultKind {
  const mapping: Record<NorthstarLedgerTask["kind"], NorthstarAttemptResultKind> = {
    research: "research-result",
    analysis: "analysis-result",
    "artboard-mutation": "artboard-mutation-draft",
    verification: "verification-result",
    finalization: "finalization-result",
  };
  return mapping[task.kind];
}

function parseResponseBase(input: Record<string, unknown>, request: NorthstarTurnRequest) {
  if (input.protocolVersion !== NORTHSTAR_TURN_PROTOCOL_VERSION) fail("INVALID_PROTOCOL_VERSION", "Response protocolVersion is invalid.");
  const requestId = stringValue(input.requestId, "$.requestId", { min: 8, max: 128 });
  if (requestId !== request.requestId) fail("STALE_RESPONSE", `Response ${requestId} does not match request ${request.requestId}.`);
  return { protocolVersion: NORTHSTAR_TURN_PROTOCOL_VERSION, requestId } as const;
}

export function parseNorthstarTurnResponse(value: unknown, request: NorthstarTurnRequest): NorthstarTurnResponse {
  validatePayloadSize(value);
  const input = record(value, "$");
  const type = enumValue(
    input.type,
    ["activity-draft", "run-ready-to-finalize", "attempt-result", "attempt-failure", "task-correction", "run-finalized", "turn-error"] as const,
    "$.type",
  );
  const base = parseResponseBase(input, request);

  if (type === "activity-draft") {
    exactKeys(input, ["protocolVersion", "requestId", "type", "activity"], [], "$");
    if (request.type !== "decide-next-activity") fail("RESPONSE_TYPE_MISMATCH", "An activity draft only answers a decision request.");
    return { ...base, type, activity: parseActivity(input.activity, "$.activity") };
  }
  if (type === "run-ready-to-finalize") {
    exactKeys(input, ["protocolVersion", "requestId", "type", "reason"], [], "$");
    if (request.type !== "decide-next-activity") fail("RESPONSE_TYPE_MISMATCH", "run-ready-to-finalize only answers a decision request.");
    return { ...base, type, reason: stringValue(input.reason, "$.reason", { max: 20_000 }) };
  }
  if (type === "attempt-result") {
    exactKeys(input, ["protocolVersion", "requestId", "type", "taskId", "attemptId", "resultKind", "result"], ["evidence"], "$");
    if (request.type !== "execute-task-attempt") fail("RESPONSE_TYPE_MISMATCH", "attempt-result only answers an execution request.");
    const taskId = stringValue(input.taskId, "$.taskId", { max: 256 });
    const attemptId = stringValue(input.attemptId, "$.attemptId", { max: 256 });
    if (taskId !== request.task.id || attemptId !== request.attempt.id) fail("STALE_RESPONSE", "Attempt response identity does not match the request.");
    const resultKind = enumValue(
      input.resultKind,
      ["research-result", "analysis-result", "artboard-mutation-draft", "verification-result", "finalization-result"] as const,
      "$.resultKind",
    );
    if (resultKind !== expectedResultKind(request.task)) {
      fail("RESULT_KIND_MISMATCH", `${resultKind} cannot complete a ${request.task.kind} task.`);
    }
    const result = ledgerValue(input.result, "$.result");
    assertNoNorthstarSystemIdentity(result, "$.result");
    const evidence = optionalLedgerValue(input.evidence, "$.evidence");
    if (evidence !== undefined) assertNoNorthstarSystemIdentity(evidence, "$.evidence");
    return {
      ...base,
      type,
      taskId,
      attemptId,
      resultKind,
      result,
      evidence,
    } satisfies NorthstarAttemptResultResponse;
  }
  if (type === "attempt-failure") {
    exactKeys(
      input,
      ["protocolVersion", "requestId", "type", "taskId", "attemptId", "failureKind", "code", "message"],
      ["correctionContext", "retryAfterMs", "evidence"],
      "$",
    );
    if (request.type !== "execute-task-attempt") fail("RESPONSE_TYPE_MISMATCH", "attempt-failure only answers an execution request.");
    const taskId = stringValue(input.taskId, "$.taskId", { max: 256 });
    const attemptId = stringValue(input.attemptId, "$.attemptId", { max: 256 });
    if (taskId !== request.task.id || attemptId !== request.attempt.id) fail("STALE_RESPONSE", "Attempt failure identity does not match the request.");
    const evidence = optionalLedgerValue(input.evidence, "$.evidence");
    if (evidence !== undefined) assertNoNorthstarSystemIdentity(evidence, "$.evidence");
    return {
      ...base,
      type,
      taskId,
      attemptId,
      failureKind: enumValue(input.failureKind, ["transient", "correctable", "terminal"] as const, "$.failureKind"),
      code: stringValue(input.code, "$.code", { max: 200 }),
      message: stringValue(input.message, "$.message", { max: 20_000 }),
      correctionContext: optionalLedgerValue(input.correctionContext, "$.correctionContext"),
      retryAfterMs: input.retryAfterMs === undefined
        ? undefined
        : finiteNumber(input.retryAfterMs, "$.retryAfterMs", { integer: true, min: 0, max: 3_600_000 }),
      evidence,
    } satisfies NorthstarAttemptFailureResponse;
  }
  if (type === "task-correction") {
    exactKeys(input, ["protocolVersion", "requestId", "type", "taskId", "action"], [], "$");
    if (request.type !== "correct-active-task") fail("RESPONSE_TYPE_MISMATCH", "task-correction only answers a correction request.");
    const taskId = stringValue(input.taskId, "$.taskId", { max: 256 });
    if (taskId !== request.task.id) fail("STALE_RESPONSE", "Correction response targets another task.");
    const actionInput = record(input.action, "$.action");
    const actionName = enumValue(actionInput.action, ["retry", "cancel", "supersede"] as const, "$.action.action");
    const action = actionName === "retry"
      ? (() => {
          exactKeys(actionInput, ["action", "executionInput"], [], "$.action");
          const executionInput = ledgerValue(actionInput.executionInput, "$.action.executionInput");
          assertNoNorthstarSystemIdentity(executionInput, "$.action.executionInput");
          return { action: "retry" as const, executionInput };
        })()
      : (() => {
          exactKeys(actionInput, ["action", "reason"], [], "$.action");
          return { action: actionName, reason: stringValue(actionInput.reason, "$.action.reason", { max: 20_000 }) };
        })();
    return { ...base, type, taskId, action } satisfies NorthstarTaskCorrectionResponse;
  }
  if (type === "run-finalized") {
    exactKeys(input, ["protocolVersion", "requestId", "type", "summary"], [], "$");
    if (request.type !== "finalize-run") fail("RESPONSE_TYPE_MISMATCH", "run-finalized only answers a finalization request.");
    const summary = ledgerValue(input.summary, "$.summary");
    assertNoNorthstarSystemIdentity(summary, "$.summary");
    return { ...base, type, summary };
  }
  exactKeys(input, ["protocolVersion", "requestId", "type", "code", "message", "retryable"], ["retryAfterMs"], "$");
  return {
    ...base,
    type,
    code: stringValue(input.code, "$.code", { max: 200 }),
    message: stringValue(input.message, "$.message", { max: 20_000 }),
    retryable: booleanValue(input.retryable, "$.retryable"),
    retryAfterMs: input.retryAfterMs === undefined
      ? undefined
      : finiteNumber(input.retryAfterMs, "$.retryAfterMs", { integer: true, min: 0, max: 3_600_000 }),
  } satisfies NorthstarTurnErrorResponse;
}

export function parseNorthstarActivityDraftModelOutput(value: unknown):
  | { decision: "activity"; activity: NorthstarActivityDraft }
  | { decision: "ready-to-finalize"; reason: string } {
  const input = record(value, "$.modelOutput");
  const decision = enumValue(input.decision, ["activity", "ready-to-finalize"] as const, "$.modelOutput.decision");
  if (decision === "activity") {
    exactKeys(input, ["decision", "activity"], [], "$.modelOutput");
    return { decision, activity: parseActivity(input.activity, "$.modelOutput.activity") };
  }
  exactKeys(input, ["decision", "reason"], [], "$.modelOutput");
  return { decision, reason: stringValue(input.reason, "$.modelOutput.reason", { max: 20_000 }) };
}

export function parseNorthstarAttemptModelOutput(value: unknown):
  | { outcome: "success"; result: NorthstarLedgerValue }
  | {
      outcome: "failure";
      failureKind: "transient" | "correctable" | "terminal";
      code: string;
      message: string;
      correctionContext?: NorthstarLedgerValue;
      retryAfterMs?: number;
    } {
  const input = record(value, "$.modelOutput");
  const outcome = enumValue(input.outcome, ["success", "failure"] as const, "$.modelOutput.outcome");
  if (outcome === "success") {
    exactKeys(input, ["outcome", "result"], [], "$.modelOutput");
    const result = ledgerValue(input.result, "$.modelOutput.result");
    assertNoNorthstarSystemIdentity(result, "$.modelOutput.result");
    return { outcome, result };
  }
  exactKeys(
    input,
    ["outcome", "failureKind", "code", "message"],
    ["correctionContext", "retryAfterMs"],
    "$.modelOutput",
  );
  return {
    outcome,
    failureKind: enumValue(input.failureKind, ["transient", "correctable", "terminal"] as const, "$.modelOutput.failureKind"),
    code: stringValue(input.code, "$.modelOutput.code", { max: 200 }),
    message: stringValue(input.message, "$.modelOutput.message", { max: 20_000 }),
    correctionContext: optionalLedgerValue(input.correctionContext, "$.modelOutput.correctionContext"),
    retryAfterMs: input.retryAfterMs === undefined
      ? undefined
      : finiteNumber(input.retryAfterMs, "$.modelOutput.retryAfterMs", { integer: true, min: 0, max: 3_600_000 }),
  };
}

export function parseNorthstarCorrectionModelOutput(value: unknown):
  | { action: "retry"; executionInput: NorthstarLedgerValue }
  | { action: "cancel" | "supersede"; reason: string } {
  const input = record(value, "$.modelOutput");
  const action = enumValue(input.action, ["retry", "cancel", "supersede"] as const, "$.modelOutput.action");
  if (action === "retry") {
    exactKeys(input, ["action", "executionInput"], [], "$.modelOutput");
    const executionInput = ledgerValue(input.executionInput, "$.modelOutput.executionInput");
    assertNoNorthstarSystemIdentity(executionInput, "$.modelOutput.executionInput");
    return { action, executionInput };
  }
  exactKeys(input, ["action", "reason"], [], "$.modelOutput");
  return { action, reason: stringValue(input.reason, "$.modelOutput.reason", { max: 20_000 }) };
}

export function parseNorthstarFinalizationModelOutput(value: unknown): { summary: NorthstarLedgerValue } {
  const input = record(value, "$.modelOutput");
  exactKeys(input, ["summary"], [], "$.modelOutput");
  const summary = ledgerValue(input.summary, "$.modelOutput.summary");
  assertNoNorthstarSystemIdentity(summary, "$.modelOutput.summary");
  return { summary };
}
