import { expect, test } from '@playwright/test';

test('precise feedback preserves live input, saved state, source scope and camera; motion review retains three real frames', async ({ page }) => {
  test.setTimeout(180000);
  await page.goto('/canvas-v2-e2e/codex');
  const send = async (message: string) => { await page.getByLabel('Message North Star').fill(message); await page.getByRole('button', { name: 'Send message', exact: true }).click(); };
  await send('screen creative');
  await expect(page.getByText('Created the screen with a saved product identity and reviewed three distinct motion frames.', { exact: true })).toBeVisible({ timeout: 90000 });
  await page.getByRole('button', { name: 'Show on canvas', exact: true }).click();
  const scene = page.getByTestId('canvas-v2-native-scene'), object = scene.locator('[data-canvas-v2-screen]');
  const frame = page.frameLocator('iframe[title="GRAET · creative review"]');
  const select = async () => { const bounds = await object.boundingBox(); if (!bounds) throw Error('Screen is not visible'); await page.mouse.click(bounds.x - 3, bounds.y + bounds.height / 2); };
  await frame.getByRole('button', { name: 'Save team', exact: true }).click();
  await frame.getByRole('textbox', { name: 'Your goal' }).fill('Score 24 goals');
  const geometry = await object.getAttribute('style'), before = await scene.evaluate(el => el.parentElement?.style.transform);
  const encoded = await object.getAttribute('data-canvas-v2-screen');
  const source = JSON.parse(Buffer.from(encoded!, 'base64').toString());
  await select();
  await page.getByRole('button', { name: 'Give feedback on screen' }).click();
  await expect(page.getByRole('button', { name:'Done selecting' })).toBeVisible();
  await expect(page.getByText('Click items to add feedback')).toHaveCount(0);
  await frame.getByRole('heading', { name: 'Your next season.', exact: true }).click();
  await expect(page.getByTestId('screen-feedback-target')).toContainText('Your next season.');
  await send('precise feedback — change this headline only');
  await expect(page.getByText('Refined only the selected headline; the saved product identity and interaction state were retained.', { exact: true })).toBeVisible({ timeout: 90000 });
  await expect(frame.getByRole('heading', { name: 'Your next chapter.', exact: true })).toBeVisible();
  await expect(frame.getByRole('textbox', { name: 'Your goal' })).toHaveValue('Score 24 goals');
  await expect(frame.getByRole('button', { name: 'Saved', exact: true })).toBeVisible();
  expect(await object.getAttribute('style')).toBe(geometry);
  expect(await scene.evaluate(el => el.parentElement?.style.transform)).toBe(before);
  const revised = JSON.parse(Buffer.from((await object.getAttribute('data-canvas-v2-screen'))!, 'base64').toString());
  expect(revised.javascript).toBe(source.javascript); expect(revised.css).toBe(source.css);
  expect(revised.productIdentityId).toBe('graet-test');
  await select();
  await expect(page.getByRole('button', { name:'Move screen' })).toHaveCount(0);
  await expect(page.getByRole('button', { name:'Review screen quality' })).toHaveCount(0);
  await page.getByRole('button', { name:'Screen version history' }).click();
  const history = page.getByRole('dialog', { name:'Screen version history' });
  await expect(history.getByRole('navigation', { name:'Screen versions' })).toContainText('Refined the selected headline');
  await expect(history.getByRole('navigation', { name:'Screen versions' })).toContainText('Starting version');
  await history.getByRole('button', { name:'Close version history' }).click();
  await expect(frame.getByRole('textbox', { name:'Your goal' })).toHaveValue('Score 24 goals');
  await expect(frame.getByRole('button', { name:'Saved',exact:true })).toBeVisible();
  await frame.getByRole('button', { name: 'Saved', exact: true }).click();
  await expect(frame.getByRole('button', { name: 'Save team', exact: true })).toBeVisible();
  await select();
  await page.getByRole('button', { name: 'Give feedback on screen' }).click();
  await frame.getByRole('heading', { name: 'Your next chapter.', exact: true }).press('Escape');
  await expect(page.getByRole('button', { name:'Done selecting' })).toHaveCount(0);
  await expect(page.getByTestId('screen-feedback-target')).toHaveCount(0);
});


test('adding an inspiration rail retains saved native screen coordinates and live state', async ({ page }) => {
  test.setTimeout(120000);
  await page.goto('/canvas-v2-e2e/codex');
  const send = async (message: string) => { await page.getByLabel('Message North Star').fill(message); await page.getByRole('button', { name: 'Send message', exact: true }).click(); };
  await send('screen creative');
  await expect(page.getByText('Created the screen with a saved product identity and reviewed three distinct motion frames.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Show on canvas', exact: true }).click();
  const screen = page.locator('[data-canvas-v2-screen]');
  const position = () => screen.evaluate(el => [el.style.getPropertyValue('--canvas-v2-native-x'), el.style.getPropertyValue('--canvas-v2-native-y')]);
  const before = await position();
  await page.frameLocator('iframe[title="GRAET · creative review"]').getByRole('button', { name: 'Save team', exact: true }).click();
  await send('creative flow preserve');
  await expect(page.getByText('Added the full inspiration flow without moving the existing screen.', { exact: true })).toBeVisible({ timeout: 90000 });
  expect(await position()).toEqual(before);
  await expect(page.locator('[data-canvas-v2-canonical-flow]')).toHaveCount(1);
  await send('creative flow preserve');
  await expect(page.getByText('Added the full inspiration flow without moving the existing screen.', { exact: true })).toHaveCount(2);
  await expect(page.locator('[data-canvas-v2-canonical-flow]')).toHaveCount(1);
  expect(await position()).toEqual(before);
  await expect(page.frameLocator('iframe[title="GRAET · creative review"]').getByRole('button', { name: 'Saved', exact: true })).toBeVisible();
});

test('runtime checks reject clipped, transparent and covered controls and hold short transitions', async ({ page }) => {
  await page.goto('/canvas-v2-e2e/codex');
  await page.getByLabel('Message North Star').fill('screen reachability');
  await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await expect(page.getByText('Hidden and covered controls were rejected; the reachable control produced three distinct 80ms motion frames.', { exact: true })).toBeVisible({ timeout: 90000 });
});


test('feedback spans screens and canvas references; restoring a version preserves siblings and geometry', async ({ page }) => {
  test.setTimeout(180000);
  await page.goto('/canvas-v2-e2e/codex');
  const send = async (message: string) => { await page.getByLabel('Message North Star').fill(message); await page.getByRole('button',{name:'Send message',exact:true}).click(); };
  for(let i=1;i<=2;i++) {
    await send('screen creative');
    await expect(page.getByText('Created the screen with a saved product identity and reviewed three distinct motion frames.',{exact:true})).toHaveCount(i,{timeout:90000});
  }
  await send('creative flow preserve');
  await expect(page.getByText('Added the full inspiration flow without moving the existing screen.',{exact:true})).toBeVisible({timeout:90000});
  await page.getByRole('button',{name:'Show on canvas',exact:true}).click();
  const screens=page.locator('[data-canvas-v2-screen]');
  const first=screens.nth(0), second=screens.nth(1);
  const firstId=await first.getAttribute('data-canvas-v2-node-id'), secondId=await second.getAttribute('data-canvas-v2-node-id');
  const frame1=page.frameLocator(`[data-canvas-v2-node-id="${firstId}"] iframe`), frame2=page.frameLocator(`[data-canvas-v2-node-id="${secondId}"] iframe`);
  await frame1.getByRole('button',{name:'Save team',exact:true}).click();
  await frame1.getByLabel('Your goal').fill('Score 24 goals');
  const geometry1=await first.getAttribute('style'),geometry2=await second.getAttribute('style');
  const canonical=page.locator('[data-canvas-v2-canonical-flow]'), reference=await canonical.getAttribute('data-canvas-v2-canonical-flow');
  const select=async()=>{const b=await first.boundingBox();if(!b)throw Error('Screen missing');await page.mouse.click(b.x-3,b.y+b.height/2);};
  await select();await page.getByRole('button',{name:'Give feedback on screen'}).click();
  await frame1.getByRole('heading',{name:'Your next season.',exact:true}).click();
  await frame2.getByRole('heading',{name:'Your next season.',exact:true}).click();
  await page.getByRole('button',{name:'Done selecting'}).click();
  const referenceLeaf=canonical.getByRole('img',{name:'Landing',exact:true});
  await referenceLeaf.click();await page.getByRole('button',{name:'Give feedback on selection',exact:true}).click();
  await expect(page.getByText('Feedback · 3 items',{exact:true})).toBeVisible();
  await send('feedback collection');
  await expect(page.getByText('Refined every tagged screen detail and retained the tagged canvas reference.',{exact:true})).toBeVisible({timeout:90000});
  await expect(frame1.getByRole('heading',{name:'Refined detail 1',exact:true})).toBeVisible();
  await expect(frame2.getByRole('heading',{name:'Refined detail 2',exact:true})).toBeVisible();
  await expect(frame1.getByLabel('Your goal')).toHaveValue('Score 24 goals');
  await expect(frame1.getByRole('button',{name:'Saved',exact:true})).toBeVisible();
  expect(await canonical.getAttribute('data-canvas-v2-canonical-flow')).toBe(reference);
  const sibling=await second.getAttribute('data-canvas-v2-screen');
  await select();await page.getByRole('button',{name:'Screen version history'}).click();
  const history=page.getByRole('dialog',{name:'Screen version history'});
  await history.getByRole('button').filter({hasText:'Starting version'}).click();
  await history.getByRole('button',{name:'Use this version',exact:true}).click();
  await expect(history).toHaveCount(0);
  await expect(frame1.getByRole('heading',{name:'Your next season.',exact:true})).toBeVisible();
  await expect(frame1.getByRole('button',{name:'Save team',exact:true})).toBeVisible();
  expect(await second.getAttribute('data-canvas-v2-screen')).toBe(sibling);
  expect(await first.getAttribute('style')).toBe(geometry1);expect(await second.getAttribute('style')).toBe(geometry2);
  await select();await page.getByRole('button',{name:'Screen version history'}).click();
  await expect(history.getByText('On canvas',{exact:true})).toHaveCount(1);
  await expect(history.getByRole('button',{name:'Applied on canvas',exact:true})).toBeDisabled();
});
