import { expect, test } from '@playwright/test';

test('precise feedback preserves live input, saved state, source scope and camera; motion review retains three real frames', async ({ page }) => {
  test.setTimeout(180000);
  await page.goto('/canvas-v2-e2e/codex');
  const send = async (message: string) => { await page.getByLabel('Message North Star').fill(message); await page.getByRole('button', { name: 'Send message', exact: true }).click(); };
  await send('screen creative');
  await expect(page.getByText('Created the screen with a saved product identity and reviewed three distinct motion frames.', { exact: true })).toBeVisible({ timeout: 90000 });
  await page.getByRole('button', { name: 'Show on canvas', exact: true }).click();
  const scene = page.getByTestId('canvas-v2-native-scene'), object = scene.locator('[data-canvas-v2-screen]');
  const frame = page.frameLocator('iframe[title="GRAET · creative review"]');
  const select = async () => { const bounds = await object.boundingBox(); if (!bounds) throw Error('Screen is not visible'); await page.mouse.click(bounds.x - 3, bounds.y + bounds.height / 2); };
  await frame.getByRole('button', { name: 'Save team', exact: true }).click();
  await frame.getByRole('textbox', { name: 'Your goal' }).fill('Score 24 goals');
  const geometry = await object.getAttribute('style'), before = await scene.evaluate(el => el.parentElement?.style.transform);
  const encoded = await object.getAttribute('data-canvas-v2-screen');
  const source = JSON.parse(Buffer.from(encoded!, 'base64').toString());
  await select();
  await page.getByRole('button', { name: 'Give feedback on screen' }).click();
  await expect(page.getByText('Choose an element to give feedback · Esc to cancel')).toBeVisible();
  await frame.getByRole('heading', { name: 'Your next season.', exact: true }).click();
  await expect(page.getByTestId('screen-feedback-target')).toContainText('Your next season.');
  await send('precise feedback — change this headline only');
  await expect(page.getByText('Refined only the selected headline; the saved product identity and interaction state were retained.', { exact: true })).toBeVisible({ timeout: 90000 });
  await expect(frame.getByRole('heading', { name: 'Your next chapter.', exact: true })).toBeVisible();
  await expect(frame.getByRole('textbox', { name: 'Your goal' })).toHaveValue('Score 24 goals');
  await expect(frame.getByRole('button', { name: 'Saved', exact: true })).toBeVisible();
  expect(await object.getAttribute('style')).toBe(geometry);
  expect(await scene.evaluate(el => el.parentElement?.style.transform)).toBe(before);
  const revised = JSON.parse(Buffer.from((await object.getAttribute('data-canvas-v2-screen'))!, 'base64').toString());
  expect(revised.javascript).toBe(source.javascript); expect(revised.css).toBe(source.css);
  expect(revised.productIdentityId).toBe('graet-test');
  await select();
  await page.getByRole('button', { name: 'Review screen quality' }).click();
  const review = page.getByRole('dialog', { name: 'Screen quality review' });
  await review.getByRole('button', { name: 'Review motion', exact: true }).click();
  await expect(review.getByAltText('Motion at 0%')).toBeVisible();
  await expect(review.getByAltText('Motion at 50%')).toBeVisible();
  await expect(review.getByAltText('Motion at 100%')).toBeVisible();
  const images = await review.locator('img[alt^="Motion at"]').evaluateAll(images => images.map(image => image.getAttribute('src')));
  expect(new Set(images).size).toBe(3);
  await review.getByRole('button', { name: 'Close screen review' }).click();
  await expect(frame.getByRole('textbox', { name: 'Your goal' })).toHaveValue('Score 24 goals');
  await expect(frame.getByRole('button', { name: 'Saved', exact: true })).toBeVisible();
  await frame.getByRole('button', { name: 'Saved', exact: true }).click();
  await expect(frame.getByRole('button', { name: 'Save team', exact: true })).toBeVisible();
  await select();
  await page.getByRole('button', { name: 'Give feedback on screen' }).click();
  await frame.getByRole('heading', { name: 'Your next chapter.', exact: true }).press('Escape');
  await expect(page.getByText('Choose an element to give feedback · Esc to cancel')).toHaveCount(0);
  await expect(page.getByTestId('screen-feedback-target')).toHaveCount(0);
});


test('adding an inspiration rail retains saved native screen coordinates and live state', async ({ page }) => {
  test.setTimeout(120000);
  await page.goto('/canvas-v2-e2e/codex');
  const send = async (message: string) => { await page.getByLabel('Message North Star').fill(message); await page.getByRole('button', { name: 'Send message', exact: true }).click(); };
  await send('screen creative');
  await expect(page.getByText('Created the screen with a saved product identity and reviewed three distinct motion frames.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Show on canvas', exact: true }).click();
  const screen = page.locator('[data-canvas-v2-screen]');
  const position = () => screen.evaluate(el => [el.style.getPropertyValue('--canvas-v2-native-x'), el.style.getPropertyValue('--canvas-v2-native-y')]);
  const before = await position();
  await page.frameLocator('iframe[title="GRAET · creative review"]').getByRole('button', { name: 'Save team', exact: true }).click();
  await send('creative flow preserve');
  await expect(page.getByText('Added the full inspiration flow without moving the existing screen.', { exact: true })).toBeVisible({ timeout: 90000 });
  expect(await position()).toEqual(before);
  await expect(page.locator('[data-canvas-v2-canonical-flow]')).toHaveCount(1);
  await send('creative flow preserve');
  await expect(page.getByText('Added the full inspiration flow without moving the existing screen.', { exact: true })).toHaveCount(2);
  await expect(page.locator('[data-canvas-v2-canonical-flow]')).toHaveCount(1);
  expect(await position()).toEqual(before);
  await expect(page.frameLocator('iframe[title="GRAET · creative review"]').getByRole('button', { name: 'Saved', exact: true })).toBeVisible();
});

test('runtime checks reject clipped, transparent and covered controls and hold short transitions', async ({ page }) => {
  await page.goto('/canvas-v2-e2e/codex');
  await page.getByLabel('Message North Star').fill('screen reachability');
  await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await expect(page.getByText('Hidden and covered controls were rejected; the reachable control produced three distinct 80ms motion frames.', { exact: true })).toBeVisible({ timeout: 90000 });
});
