import path from "node:path";
import { expect, test } from "@playwright/test";

test("video is a clean native frame and Space toggles playback without moving or revising it", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.route("**/api/canvas-v2/**", route => route.abort());
  await page.goto("/canvas");
  const scene = page.getByTestId("canvas-v2-native-scene");
  await expect(scene).toHaveCount(1);
  await page.getByRole("button",{name:"More creation tools",exact:true}).click();
  await page.getByRole("tab",{name:"Media",exact:true}).click();
  await page.getByLabel("Choose playable media",{exact:true}).setInputFiles(path.resolve("e2e/fixtures/media/canvas-motion.mp4"));
  const media = scene.locator("[data-canvas-v2-media]");
  await expect(media).toHaveCount(1);
  await expect(page.getByRole("button",{name:"Play selected media",exact:true})).toBeVisible();
  const geometry = await media.boundingBox();
  expect(geometry!.width/geometry!.height).toBeCloseTo(16/9,2);
  await expect(media).toHaveCSS("background-color","rgba(0, 0, 0, 0)");
  await expect(media).toHaveCSS("border-radius","0px");
  await expect(page.getByRole("button",{name:"Connect primitive interaction",exact:true})).toHaveCount(0);
  const revision = await scene.getAttribute("data-revision-id");
  const video = scene.locator("video");
  const workspace = page.getByRole("region",{name:"Canvas workspace",exact:true});
  await workspace.focus();
  await workspace.press("Space");
  await expect.poll(()=>video.evaluate(v=>(v as HTMLVideoElement).paused)).toBe(false);
  await workspace.press("Space");
  await expect.poll(()=>video.evaluate(v=>(v as HTMLVideoElement).paused)).toBe(true);
  expect(await scene.getAttribute("data-revision-id")).toBe(revision);
  expect(await media.boundingBox()).toEqual(geometry);
  await page.getByRole("button",{name:"Undo canvas action",exact:true}).click();
  await expect(media).toHaveCount(0);
  await page.getByRole("button",{name:"Redo canvas action",exact:true}).click();
  await expect(media).toHaveCount(1);
  await expect.poll(()=>video.evaluate(v=>(v as HTMLVideoElement).readyState)).toBeGreaterThanOrEqual(1);
  expect(errors).toEqual([]);
});

test("video and GIF batch upload keeps both sources through history and duplication", async ({page}) => {
  await page.route("**/api/canvas-v2/**", route=>route.abort());
  await page.goto("/canvas");
  await expect(page.getByTestId("canvas-v2-native-scene")).toHaveCount(1);
  await page.getByRole("button",{name:"More creation tools",exact:true}).click();
  await page.getByRole("tab",{name:"Media",exact:true}).click();
  await page.getByLabel("Choose playable media",{exact:true}).setInputFiles(["canvas-motion.mp4","canvas-motion.gif"].map(name=>path.resolve("e2e/fixtures/media",name)));
  const media=page.locator("[data-canvas-v2-playable-media]");
  await expect(media).toHaveCount(2);
  await page.getByRole("button",{name:"Play GIF",exact:true}).click();
  await expect(media.locator("img")).toHaveCount(1);
  await page.getByRole("button",{name:"Pause GIF",exact:true}).click();
  await expect(media.locator("img")).toHaveCount(0);
  await page.getByRole("button",{name:"Undo canvas action",exact:true}).click();
  await expect(media).toHaveCount(0);
  await page.getByRole("button",{name:"Redo canvas action",exact:true}).click();
  await expect(media).toHaveCount(2);
  await page.getByRole("button",{name:"Duplicate selected elements",exact:true}).click();
  await expect(media).toHaveCount(4);
});
