// lib/data.ts
import { supabase } from './supabase';

// --- TYPES ---
export interface MobileInteraction { section: string; clicked_text: string; screenshots: string[]; }
export interface MobileTab { name: string; survey_screenshots: string[]; interactions: MobileInteraction[]; }
export interface MobileSession { app: string; tabs: MobileTab[]; }
export interface WebManifest { flow_name: string; url: string; screenshots: string[]; }

export interface SocialPost {
  id?: string;
  platform: string;
  entity: string;
  url?: string;

  // Clean post body generated by the monitor for frontend display.
  post_text?: string;

  // Full scraped card/page text kept as a fallback/debug field.
  raw_text?: string;

  screenshot: string;
  timestamp?: string;

  comments?: Array<string | { author?: string; text?: string }>;

  meta?: {
    sentiment?: string;
    category?: string;
    summary?: string;
    topic_tags?: string[];
    post_date?: string;
    is_relevant?: boolean;
  };

  // Used by some Instagram grid records.
  type?: string;
  comments_screenshot?: string | null;
}

export interface BusinessPage { name: string; url: string; screenshots: string[]; intelligence?: any; }
export interface BusinessJob { title: string; url: string; captured?: boolean; screenshots?: string[]; text_file?: string; intelligence?: any; }
export interface BusinessManifest { company: string; timestamp: string; pages: BusinessPage[]; jobs: BusinessJob[]; }
export interface RosterPerson { name: string; role: string; type: string; socials?: { linkedin?: string; twitter?: string; instagram?: string; }; profile_screenshots?: string; }
export interface DeltaChange { pillar: "Mobile" | "Web"; section: string; severity: "HIGH" | "MEDIUM" | "LOW"; description: string; image_old?: string; image_new?: string; }
export interface DeltaReport { timestamp: string; compared_against: string; tracking_period?: string; changes: DeltaChange[]; }
export interface CompanyMeta { id: string; name: string; lastScan: string; }

// --- HELPERS ---

// 1. OPTIMIZED: Get List of Tracked Companies via DB instead of slow Storage directory scans
export async function getTrackedCompanies(tenantId: string): Promise<CompanyMeta[]> {
  if (!tenantId) return [];
  
  const { data, error } = await supabase
    .from('target_apps')
    .select('app_name, last_scan')
    .eq('tenant_id', tenantId);
    
  if (error || !data) {
    console.error("Failed to fetch tracked companies from DB:", error);
    return [];
  }
  
  return data.map(app => ({
    id: app.app_name,
    name: app.app_name.charAt(0).toUpperCase() + app.app_name.slice(1),
    lastScan: app.last_scan || new Date().toISOString().split('T')[0] 
  }));
}

// 2. OPTIMIZED: Get All Snapshots via DB instead of slow Storage directory scans
export async function getAvailableSnapshots(tenantId: string, companyId: string): Promise<string[]> {
  if (!tenantId || !companyId) return [];
  
  // ilike handles case-sensitivity issues gracefully
  const { data, error } = await supabase
    .from('app_snapshots')
    .select('snapshot_id')
    .eq('tenant_id', tenantId)
    .ilike('app_name', companyId)
    .order('snapshot_id', { ascending: true });

  if (error || !data) {
    console.error("Failed to fetch snapshots from DB:", error);
    return [];
  }
  
  return data.map(s => s.snapshot_id);
}

// --- MAIN DATA LOADER ---
export async function getDashboardData(tenantId: string, companyId: string, specificSnapshotId?: string) {
  if (!tenantId || !companyId) return null;
  
  let snapshotId = specificSnapshotId;

  if (!snapshotId) {
    const snapshots = await getAvailableSnapshots(tenantId, companyId);
    if (snapshots.length > 0) {
      snapshotId = snapshots[0]; 
    }
  }

  if (!snapshotId) return null;

  const publicUrl = `${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/data`;
  
  // Force the companyId to be lowercase to match the lowercase folder structure in your 'data' bucket
  const safeCompanyId = companyId.toLowerCase();

  // Fetching direct JSON by its direct URL is O(1) and extremely fast.
  const readJson = async (subPath: string) => {
    try {
      const res = await fetch(`${publicUrl}/${tenantId}/${safeCompanyId}/snapshots/${snapshotId}/${subPath}`, { next: { revalidate: 300 } });
      if (!res.ok) return null;
      return await res.json();
    } catch (error) {
      return null;
    }
  };

  // Fetch all pillars in parallel for speed, including a list of business screenshot filenames
  const [mobileData, webData, marketingData, businessData, rosterData, deltaReport, screenshotsList] = await Promise.all([
    readJson('product/mobile/session_manifest.json') as Promise<MobileSession | null>,
    readJson('product/web/ui_manifest.json') as Promise<WebManifest[] | null>,
    readJson('marketing/master_feed.json') as Promise<SocialPost[] | null>,
    readJson('business/master_manifest.json') as Promise<BusinessManifest | null>,
    readJson(`business/${safeCompanyId}_omni_roster.json`) as Promise<RosterPerson[] | null>,
    readJson('product/delta_report.json') as Promise<DeltaReport | null>,
    supabase.storage.from('data').list(`${tenantId}/${safeCompanyId}/snapshots/${snapshotId}/business/screenshots`, { limit: 100 })
  ]);

  return {
    id: companyId,
    snapshotId: snapshotId,
    mobile: mobileData,
    web: webData,
    marketing: marketingData,
    business: businessData,
    roster: rosterData,
    deltaReport: deltaReport,
    businessScreenshots: (screenshotsList.data || []).map(f => f.name) // Pass list of filenames directly
  };
}
